// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"path":"/user/login","layout":false,"name":"login","parentId":"1","id":"2"},"3":{"path":"/user","redirect":"/user/login","parentId":"1","id":"3"},"4":{"path":"/user/*","parentId":"1","id":"4"},"5":{"path":"/dashboard","name":"dashboard","icon":"dashboard","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/projects","name":"projects","icon":"project","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/projects","redirect":"/projects/list","parentId":"6","id":"7"},"8":{"path":"/projects/list","name":"list","parentId":"6","id":"8"},"9":{"path":"/projects/board","name":"board","parentId":"6","id":"9"},"10":{"path":"/statistics","name":"statistics","icon":"barChart","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"/reports","name":"reports","icon":"fileText","parentId":"ant-design-pro-layout","id":"11"},"12":{"path":"/knowledge","name":"knowledge","icon":"book","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"13"},"14":{"path":"/*","parentId":"ant-design-pro-layout","id":"14"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__user__login__index" */'@/pages/user/login/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__dashboard__workplace__index" */'@/pages/dashboard/workplace/index.tsx')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__projects__index" */'@/pages/projects/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__projects__board" */'@/pages/projects/board.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__statistics__index" */'@/pages/statistics/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__reports__index" */'@/pages/reports/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__knowledge__index" */'@/pages/knowledge/index.tsx')),
'13': React.lazy(() => import('./EmptyRoute')),
'14': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/baiyk/Desktop/workspace/outbook/customized-data-analysis-system/project-analysis/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
