/**
 * Mock 数据 - 当飞书配置缺失时使用
 * 这些数据与前端 Mock 数据保持一致
 */

export function getMockProjects() {
  return [
    {
      id: '1',
      name: '清华大学智慧校园系统',
      school: '清华大学',
      amount: 1200000,
      cost: 720000,
      profit: 480000,
      profitRate: 40,
      status: '已完成',
      startDate: '2024-01-15',
      endDate: '2024-06-30',
      manager: { id: '1', name: '张三', en_name: 'Zhang San' },
      members: [
        { id: '1', name: '张三', en_name: 'Zhang San' },
        { id: '2', name: '李四', en_name: 'Li Si' },
      ],
      description: '为清华大学打造的智慧校园管理系统',
      progress: 100,
      bugCount: 45,
      ticketCount: 12,
    },
    {
      id: '2',
      name: '北京大学在线教育平台',
      school: '北京大学',
      amount: 980000,
      cost: 588000,
      profit: 392000,
      profitRate: 40,
      status: '进行中',
      startDate: '2024-03-01',
      endDate: '2024-09-30',
      manager: { id: '3', name: '王五', en_name: 'Wang Wu' },
      members: [
        { id: '3', name: '王五', en_name: 'Wang Wu' },
        { id: '4', name: '赵六', en_name: 'Zhao Liu' },
      ],
      description: '在线教育平台开发',
      progress: 65,
      bugCount: 32,
      ticketCount: 8,
    },
    {
      id: '3',
      name: '复旦大学科研管理系统',
      school: '复旦大学',
      amount: 1500000,
      cost: 900000,
      profit: 600000,
      profitRate: 40,
      status: '进行中',
      startDate: '2024-02-20',
      endDate: '2024-10-31',
      manager: { id: '5', name: '孙七', en_name: 'Sun Qi' },
      members: [
        { id: '5', name: '孙七', en_name: 'Sun Qi' },
        { id: '6', name: '周八', en_name: 'Zhou Ba' },
      ],
      description: '科研项目管理系统',
      progress: 55,
      bugCount: 28,
      ticketCount: 6,
    },
    {
      id: '4',
      name: '上海交通大学学生管理平台',
      school: '上海交通大学',
      amount: 850000,
      cost: 510000,
      profit: 340000,
      profitRate: 40,
      status: '进行中',
      startDate: '2024-04-10',
      endDate: '2024-11-30',
      manager: { id: '7', name: '吴九', en_name: 'Wu Jiu' },
      members: [
        { id: '7', name: '吴九', en_name: 'Wu Jiu' },
        { id: '8', name: '郑十', en_name: 'Zheng Shi' },
      ],
      description: '学生信息管理平台',
      progress: 45,
      bugCount: 18,
      ticketCount: 4,
    },
    {
      id: '5',
      name: '浙江大学图书馆管理系统',
      school: '浙江大学',
      amount: 680000,
      cost: 408000,
      profit: 272000,
      profitRate: 40,
      status: '规划中',
      startDate: '2024-07-01',
      endDate: '2025-01-31',
      manager: { id: '9', name: '钱十一', en_name: 'Qian Shiyi' },
      members: [],
      description: '图书馆数字化管理系统',
      progress: 0,
      bugCount: 0,
      ticketCount: 0,
    },
    {
      id: '6',
      name: '中国科学技术大学课程管理系统',
      school: '中国科学技术大学',
      amount: 1100000,
      cost: 660000,
      profit: 440000,
      profitRate: 40,
      status: '已完成',
      startDate: '2023-09-01',
      endDate: '2024-03-31',
      manager: { id: '10', name: '孙十二', en_name: 'Sun Shier' },
      members: [
        { id: '10', name: '孙十二', en_name: 'Sun Shier' },
        { id: '11', name: '李十三', en_name: 'Li Shisan' },
      ],
      description: '课程管理与选课系统',
      progress: 100,
      bugCount: 27,
      ticketCount: 6,
    },
    {
      id: '7',
      name: '南京大学实验室预约系统',
      school: '南京大学',
      amount: 450000,
      cost: 270000,
      profit: 180000,
      profitRate: 40,
      status: '规划中',
      startDate: '2024-08-01',
      endDate: '2025-02-28',
      manager: { id: '12', name: '周十四', en_name: 'Zhou Shisi' },
      members: [],
      description: '实验室预约与管理系统',
      progress: 0,
      bugCount: 0,
      ticketCount: 0,
    },
  ];
}

export function getMockBugs() {
  return [
    {
      id: 'bug-1',
      projectId: '1',
      projectName: '清华大学智慧校园系统',
      title: '登录页面样式错乱',
      description: '在移动端登录页面样式显示不正常',
      severity: '中',
      status: '已解决',
      assignee: { id: '2', name: '李四', en_name: 'Li Si' },
      reporter: { id: '1', name: '张三', en_name: 'Zhang San' },
      createdAt: '2024-05-10 10:30:00',
      resolvedAt: '2024-05-11 15:20:00',
    },
    {
      id: 'bug-2',
      projectId: '2',
      projectName: '北京大学在线教育平台',
      title: '视频播放卡顿',
      description: '在线视频播放时出现卡顿现象',
      severity: '高',
      status: '处理中',
      assignee: { id: '4', name: '赵六', en_name: 'Zhao Liu' },
      reporter: { id: '3', name: '王五', en_name: 'Wang Wu' },
      createdAt: '2024-06-15 14:20:00',
      resolvedAt: '',
    },
  ];
}

export function getMockTickets() {
  return [
    {
      id: 'ticket-1',
      projectId: '1',
      projectName: '清华大学智慧校园系统',
      title: '数据库性能优化',
      type: '维护',
      status: '已完成',
      priority: '高',
      assignee: { id: '1', name: '张三', en_name: 'Zhang San' },
      createdAt: '2024-06-01 09:00:00',
      completedAt: '2024-06-05 17:00:00',
    },
    {
      id: 'ticket-2',
      projectId: '2',
      projectName: '北京大学在线教育平台',
      title: '添加新功能模块',
      type: '修复',
      status: '处理中',
      priority: '中',
      assignee: { id: '3', name: '王五', en_name: 'Wang Wu' },
      createdAt: '2024-06-10 10:30:00',
      completedAt: '',
    },
  ];
}

export function getMockMembers() {
  return [
    {
      id: '1',
      name: '张三',
      position: '高级工程师',
      projects: ['清华大学智慧校园系统'],
      workDays: 120,
      bugCount: 15,
      efficiency: 85,
    },
    {
      id: '2',
      name: '李四',
      position: '项目经理',
      projects: ['清华大学智慧校园系统', '北京大学在线教育平台'],
      workDays: 150,
      bugCount: 25,
      efficiency: 75,
    },
    {
      id: '3',
      name: '王五',
      position: '前端工程师',
      projects: ['北京大学在线教育平台'],
      workDays: 90,
      bugCount: 12,
      efficiency: 88,
    },
  ];
}

export function getMockKnowledgeDocs() {
  return [
    {
      id: 'doc-1',
      title: '清华大学智慧校园系统需求文档',
      type: '需求',
      projectId: '1',
      projectName: '清华大学智慧校园系统',
      status: '已发布',
      author: { id: '1', name: '张三', en_name: 'Zhang San' },
      content: '系统需求详细说明...',
      url: 'https://example.com/doc1',
      createdAt: '2024-01-10',
      updatedAt: '2024-01-15',
    },
    {
      id: 'doc-2',
      title: '北京大学在线教育平台设计文档',
      type: '设计',
      projectId: '2',
      projectName: '北京大学在线教育平台',
      status: '草稿',
      author: { id: '3', name: '王五', en_name: 'Wang Wu' },
      content: '系统设计详细说明...',
      url: 'https://example.com/doc2',
      createdAt: '2024-02-20',
      updatedAt: '2024-03-01',
    },
  ];
}

