// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/baiyk/Desktop/workspace/outbook/customized-data-analysis-system/project-analysis/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import ProjectOutlined from '/Users/baiyk/Desktop/workspace/outbook/customized-data-analysis-system/project-analysis/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProjectOutlined';
import BarChartOutlined from '/Users/baiyk/Desktop/workspace/outbook/customized-data-analysis-system/project-analysis/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import FileTextOutlined from '/Users/baiyk/Desktop/workspace/outbook/customized-data-analysis-system/project-analysis/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import BookOutlined from '/Users/baiyk/Desktop/workspace/outbook/customized-data-analysis-system/project-analysis/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BookOutlined';
export default { DashboardOutlined, ProjectOutlined, BarChartOutlined, FileTextOutlined, BookOutlined };
